pipeline {
    agent any
    environment {
        game = 'overwatch2'
    }
    stages {
        stage('Init') {
            steps {
                // 상태값 확인
                echo "Running ${env.BUILD_ID} on ${env.JENKINS_URL}"
                echo "JAVA_HOME=${env.JAVA_HOME}"
                echo "JOB_NAME=${env.JOB_NAME}"
                echo "NODE_NAME=${env.NODE_NAME}"
                echo "WORKSPACE=${env.WORK_SPACE}"
            }
        }
        stage('Build') {
            steps {
                echo 'Building..'
            }
        }
        stage('Test') {
            steps {
                echo 'Testing..'
            }
        }
        stage('Deploy') {
            steps {
                echo 'Deploying....'
            }
        }
    }
}